//
//  Config.swift
//  PlayMe
//
//  Created by Richard Robinson on 8/30/16.
//  Copyright © 2016 WEBDMG. All rights reserved.
//

import Foundation

/// Config class for base urls of a Gathr Project
open class Config:NSObject{
    //MARK: - Properties
    /// Users blog URL to pull articles from. Set by the user.
    public var blogurl = ""
    /// Apple ID of the app in the appstore. Set by the user.
    public var playmeappappleid = ""
    /// URL to social site of user. Set by the user.
    public var playmeappfacebookurl = ""
    /// URL to users website. Set by the user.
    public var playmeapphomeurl = ""
    /// ID of app set by Gathr system.
    public var playmeappid = ""
    /// URL to users website. Set by the user.
    public var playmeappinstagramurl = ""
    /// Search keywords set by user. Use primarly for podcasts.
    public var playmeappkeywords = ""
    /// Flag to set or determine if microsite app promo landing page is active (visible to external users.)
    public var playmeapplandingpageactive = ""
    /// Name of app in the Gathr System set by admin
    public var playmeappname = ""
    /// Vanity version of the playmeappname set by admin
    public var playmeappnameformatted = ""
    /// Url to e-com store for use in a webview for selling merch. Set by the user.
    public var playmeappstoreurl = ""
    /// Token generated by the Gathr sytem to identify the app
    public var playmeapptoken = ""
    /// URL to users website. Set by the user.
    public var playmeapptwitterurl = ""
    /// TOken generated by the Gathr sytem to identifiy a specific app owner.
    public var playmetoken = ""
    /// A list of the features enabled for this user.
    public var playmefeatures = NSDictionary()
    
    //MARK: - Init method
    /// Init to create Config object
     /// - Parameter data: json data set to a dictionary
    public init?(response:NSDictionary) {
        self.blogurl = (((response.value(forKey: "config") as AnyObject).value(forKey: "blogurl") as AnyObject).object(at: 0)) as! String
        self.playmeappappleid = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeappappleid") as AnyObject).object(at: 0)) as! String
        self.playmeappfacebookurl = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeappfacebookurl") as AnyObject).object(at: 0)) as! String
        self.playmeapphomeurl = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeapphomeurl") as AnyObject).object(at: 0)) as! String
        self.playmeappid = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeappid") as AnyObject).object(at: 0)) as! String
        self.playmeappinstagramurl = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeappinstagramurl") as AnyObject).object(at: 0)) as! String
        //self.playmeappkeywords = (response.valueForKey("config")?.valueForKey("playmeappkeywords")?.objectAtIndex(0))! as! String
        self.playmeapplandingpageactive = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeapplandingpageactive") as AnyObject).object(at: 0)) as! String
        self.playmeappname = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeappname") as AnyObject).object(at: 0)) as! String
        self.playmeappnameformatted = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeappnameformatted") as AnyObject).object(at: 0)) as! String
        self.playmeappstoreurl = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeappstoreurl") as AnyObject).object(at: 0)) as! String
        self.playmeapptoken = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeapptoken") as AnyObject).object(at: 0)) as! String
        self.playmeapptwitterurl = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmeapptwitterurl") as AnyObject).object(at: 0)) as! String
        self.playmetoken = (((response.value(forKey: "config") as AnyObject).value(forKey: "playmetoken") as AnyObject).object(at: 0)) as! String
        let two = response.value(forKey:"config") as! NSArray
        self.playmefeatures = two.object(at: 1) as! NSDictionary
    }
    
    //MARK: - To method
    /// Convert Object to Dictionary
    open func toDictionary() -> NSDictionary {
        let configDictionary = [
            "blogurl": self.blogurl,
            "playmeappappleid": self.playmeappappleid,
            "playmeappfacebookurl": self.playmeappfacebookurl,
            "playmeapphomeurl": self.playmeapphomeurl,
            "playmeappid": self.playmeappid,
            "playmeappinstagramurl": self.playmeappinstagramurl,
            "playmeappkeywords": self.playmeappkeywords,
            "playmeapplandingpageactive": self.playmeapplandingpageactive,
            "playmeappname": self.playmeappname,
            "playmeappnameformatted": self.playmeappnameformatted,
            "playmeappstoreurl": self.playmeappstoreurl,
            "playmeapptoken": self.playmeapptoken,
            "playmeapptwitterurl": self.playmeapptwitterurl,
            "playmetoken": self.playmetoken,
            "playmefeatures": self.playmefeatures
        ] as [String : Any]
        return configDictionary as NSDictionary
    }
}
